### ISSUE TITLE
Hero Text

### ISSUE THREAD

**Issue by mivons** [alexcape/escapehatch-website#1]
Once we get to 1500px browser width can we have the headline lock-up (including "for the modern web") have a max width of 80%. Its getting to tight to the edge of the browser. Keep this change until your 690 breakpoint.

1500px-691px

![image](https://user-images.githubusercontent.com/32840979/36233967-820d204e-11b6-11e8-8873-ce87bd68aa08.png)

**Comment by alexcape** [comment]
**Change made.**
_Keep in mind most screens are not even 1500px wide so this change will affect a majority of users including myself - this decreased the hero width fairly substantially compared to the way it appeared before. This may be a better candidate for a media query based on viewport height if you're concerned about overlap with the logo as in your screenshot._

**Comment by alexcape** [comment]
**Pushed to stage.**

**Comment by mivons** [comment]
Can we cap this adjustment at 1500px browser width. It now gets huge on larger screens.

It looks really good now below 1500
