### ISSUE TITLE
Build your escape hatch - Gradient

### ISSUE THREAD

**Issue by mivons** [alexcape/escapehatch-website#11]
Can we get the transparent gradient on both desktop and mobile a bit less transparent. 

Trying to get the text more legible on the background image

**Comment by alexcape** [comment]
**Changed, pushed**

Previously: `linear-gradient(transparent 10%, rgba(26,149,137,1)`
Now: `linear-gradient(rgba(26,149,137,0.6) 50%, rgba(26,149,137,1)`
