### ISSUE TITLE
Sky Quest - Slider Alignment

### ISSUE THREAD

**Issue by mivons** [alexcape/escapehatch-website#12]
Alignment is slightly off. Can we move over the entire slider 10px to the right to better align to the text?

Also look at slide dots/dashes aligment. Looks light it might be 10px off the edge of the slide

**_This bug is for mobile, tablet and desktop_**

**Slide Alignment**
![screenshot 2018-02-14 20 13 04](https://user-images.githubusercontent.com/32840979/36236375-c4c515e2-11c3-11e8-89a6-b030d8556910.png)

**Slide Dots/Dashes Alignment**
![screenshot 2018-02-14 20 19 00](https://user-images.githubusercontent.com/32840979/36236526-85152f26-11c4-11e8-9719-f7facff9f097.png)

**Comment by alexcape** [comment]
**Fixed, pushed.**
