### ISSUE TITLE
Brands We Work With - Logo Margins

### ISSUE THREAD

**Issue by mivons** [alexcape/escapehatch-website#16]
Make logos go all the way to the edge of the container . This also be how it would break down for tablet and mobile too. 

![screenshot 2018-02-14 20 36 33](https://user-images.githubusercontent.com/32840979/36236899-c20766ae-11c6-11e8-8075-8a68dd4dbe18.png)

**Comment by alexcape** [comment]
**fixed, pushed - but may need to revisit due to the other bug**

this is working from a margin perspective - the other related bug is much more cumbersome than this because of wrapping.

**Comment by alexcape** [comment]
**This is working on stage. Up for review.**
