### ISSUE TITLE
Brands We Work With - Tablet/Mobile - Logos

### ISSUE THREAD

**Issue by mivons** [alexcape/escapehatch-website#17]
Always display logos in two columns on tablet and mobile. We can reduce width of logo on mobile.

I had a 200px max width on desktop and 120px on mobile

**Comment by alexcape** [comment]
this is turning out to be more difficult than originally thought, also may need to know the exact number of logos ahead of time - will revisit

**Comment by alexcape** [comment]
**Fixed, pushed.**

I have the logos reducing now, they didn't look right until we got down to the small 450px BP but I also have them stuck to the outsides like you asked in ticket #16 . Up for review.
