### ISSUE TITLE
Contact Us - Submit Btn

### ISSUE THREAD

**Issue by mivons** [alexcape/escapehatch-website#20]
Can we increase the size of this button? Its currently about 10px less in height than the btn in the Sky Quest section. I'd like both buttons to be identical in height if thats possible

**Comment by alexcape** [comment]
**Fixed, pushed.**

This should be fixed, was a problem with the line-height on a button element. Button looks like a chode now kind of but it should be `padding: 12px 35px;`

**Comment by mivons** [comment]
height looks good. can we adjust the width to be the same as the visit website button?

**Comment by alexcape** [comment]
**Got it, pushing.**

Solution: `padding: 12px 59px; left: 87px;`
