### ISSUE TITLE
Fly Sky Quest - Mobile - Slider

### ISSUE THREAD

**Issue by mivons** [alexcape/escapehatch-website#24]
Reduce space between slide and dots to 20px

**Comment by alexcape** [comment]
**Fixed, pushed.**

Multiple issues fixed in slick-theme.css, `font-size: 0; line-height: 0; bottom: -40px;`

**Comment by mivons** [comment]
Shit, i guess we should also make this change for tablet

**Comment by alexcape** [comment]
**Okay, try now**
