### ISSUE TITLE
Mobile Spacing for absolute positioned items

### ISSUE THREAD

**Issue by mivons** [alexcape/escapehatch-website#25]
For mobile, fudge both "sky quest" and "contact us" at the bottom to be closer to 80px margin

For tablet and desktop also fudge to be closer to 160px

**Comment by alexcape** [comment]
just to confirm, you want the dots to move closer to the slider and you want the bottom margin adjusted to 80px at the same time correct? both should happen at our 690/mobile BP?

**Comment by alexcape** [comment]
**pushing so you can see for yourself**

**Comment by mivons** [comment]
whatever you did it looks perfect

**Comment by mivons** [comment]
Did you also tweak the spacing between the submit button and bottom of container?

**Comment by alexcape** [comment]
**Issue should be resolved on the button spacing. Pushed.**

solution: 56px buffer padding on bottom of form to compensate
