### ISSUE TITLE
Sky Quest - Button

### ISSUE THREAD

**Issue by mivons** [alexcape/escapehatch-website#27]
On mobile, add an additional 10px after the button. Final should be 80px

On tablet, add another 80px after the button. Final should be 160px

**Comment by alexcape** [comment]
Just wanted to confirm that you're talking about the space between the VISIT WEBSITE button and the slider correct?!

**Comment by mivons** [comment]
correct

**Comment by alexcape** [comment]
**This should be resolved, pushed.**

Solution: 3 BP's (accounted for the image switch @900px) where padding on .slickcontainer were adjusted
