### ISSUE TITLE
We're escape hatch - Tablet

### ISSUE THREAD

**Issue by mivons** [alexcape/escapehatch-website#5]
Increase margin on main container. Its currently 30. Lets look at increasing it to 80px, left and right

**Comment by alexcape** [comment]
Can please include breakpoints or something, 80px down to what screensize? If I were to just do 80px margin on both sides the text gets squeezed once we hit tablet

**Comment by alexcape** [comment]
**Changes made, Pushed**
I have this going back to 40px margins after the 1023px BP but around 630px we're starting to get squeezed. May want to hit the column layout sooner than 500px BP.

**Comment by alexcape** [comment]
Discussed changes, pushed.

**Comment by mivons** [comment]
Looks like it reverted back to 40px of padding left and right. Can we put it back to 80px?

**Comment by alexcape** [comment]
**Whoops, try now**

**Comment by mivons** [comment]
Not seeing the change
