### ISSUE TITLE
Mobile Margin at top and bottom of each section

### ISSUE THREAD

**Issue by mivons** [alexcape/escapehatch-website#8]
Make it 80px. This includes the "See ya Starbucks" section

**Comment by alexcape** [comment]
Should be good, pushed.

Note: because of the way certain elements are positioned, i.e. the submit button the form, they're not counted in the padding/margins on containers so we may have to compensate by adding small amounts to the padding/margins.

**Comment by mivons** [comment]
I added a new ticket about spacing for absolute positioned items. For the "How We Build Your Escape Hatch" section you have an additional 40px of padding on the bottom of the last paragraph. Can we remove this? Right now it looks like its has 120px of padding total

**Comment by alexcape** [comment]
Hmmm... taking this to slack to talk through.

**Comment by alexcape** [comment]
**Pushed**

Solution: `article:nth-child(3) {padding:0;}`
