### ISSUE TITLE
Desktop Margin at top and bottom of each section

### ISSUE THREAD

**Issue by mivons** [alexcape/escapehatch-website#9]
Double check that all are 160px top and bottom

**Comment by alexcape** [comment]
**Should be good, pushed.**

_Note: because of the way certain elements are positioned, i.e. the submit button the form, they're not counted in the padding/margins on containers so we may have to compensate by adding small amounts to the padding/margins._

**Comment by mivons** [comment]
Everything looks good. Just reference my ticket for absolute positioned items to fully complete this ticket.
